title:              Analitica-bit
email:              matthewefoli@gmail.com
description:        Data tutorials, tips, tricks and projects
author:             Analitica-bit
baseurl:            ""
url:                "https://analitica-bit.github.io"

# Social Profiles
twitter_username:   
github_username:    efolimatthew
facebook_username:  
instagram_username:  
linkedin_username: matthew-efoli-1b64ab187

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
future: falsess
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
